# -*- coding: utf-8 -*-
"""banking_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFxWotlILKEbA0dVXy_imdhwyJlKQcPA
"""

class BankAccount:

    def __init__(self, name, balance):
        self.name = name
        self.balance = balance

    def deposit(self, amount):
        self.balance = self.balance + amount
        print("Money deposited successfully")

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance = self.balance - amount
            print("Money withdrawn successfully")
        else:
            print("Insufficient balance")

    def show_balance(self):
        print("Name:", self.name)
        print("Balance:", self.balance)


# Creating object
account = BankAccount("Ammu", 5000)

account.show_balance()

account.deposit(1000)

account.withdraw(2000)

account.show_balance()